#index:
#    path: /
#    controller: App\Controller\DefaultController::index

myagency:
    path: /
    controller: App\Controller\HomeController::base
home:
    path: /home/
    controller: App\Controller\HomeController::index
property:
    path: /property/
    controller: App\Controller\PropertyController::index
